# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings

title: Kerr Ring
email: kerr.ring.band@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Kerr Ring is an American 6-piece gothic metal band telling dark stories of death and misfortune.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kerr-ring.com/" 
#url: "http://127.0.0.1:4000/"
facebook_username: "kerr.ring"
#twitter_username: ""
instagram_username: "kerr.ring"
soundcloud_username:  "kerr-ring"
bandcamp_username: "kerrring"
youtube_username: "UCWYUJMCBPugQP1zoWeTghVw"
#discus_shortname: ""
share: false

# Owner/author information
owner:
  name:   Kerr Ring
  avatar: avatar.png
  favicon: favicon.ico
  info: official band website

# Settings for comments helper
# Set 'provider' to the comment provider you want to use. (i.e.  Disqus, Intense Debate, livefyre, or Facebook Comments)
# Set 'provider' to false to turn commenting off globally.
#Set 'provider: false' to disable comments globally.
# Disable comments for individual pages/posts by specifying 'comments: false' in the page/post YAML Front Matter.
#
# comments :
#   provider : disqus
#   disqus :
#     short_name : ""

# Internal nav
nav:
  - MUSIC: "/music/"  
  - MEDIA: "/gallery/"
  - SHOWS: "/shows/"  
  - NEWS: "/journal/"
  - ABOUT: "/about/"

# All translation keys
translations:
 # 404.html
  permalink: "/404.html"

# Server
destination:      	 ./_site
port:             	 4000


# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
paginate_path: "/journal/page:num/"
permalink: "/journal/:title/"
categories_path: "/journal/category/"
tags_path: "/journal/tag/"
gems: 
 - jekyll-paginate
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

#logo 492 106
# SiteMap
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/writing/"
    change_frequency_name: "change_frequency"
    priority_name: "priority"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
